### ISSUE TITLE
Please add me as a maintainer

### ISSUE THREAD

**Issue by grettke** [org2blog/metaweblog#5]
@punchagan In order to maintain org2blog I also need to maintain metaweblog. They are inseparable.

**Comment by grettke** [comment]
@punchagan Thank you! :)

**Comment by punchagan** [comment]
@grettke Thank you for all the work you have been doing on org2blog.  Hopefully, creating an organisation gives you more control to the projects, and gives you enough to steer the project in the direction that you see fit. :+1:

**Comment by grettke** [comment]
@punchagan Thank you for your kind words. Anything is possible and you made huge part of that possible!
