### ISSUE TITLE
Release a 1.0 version

### ISSUE THREAD

**Issue by grettke** [org2blog/metaweblog#6]
The last change in functionality was on Oct 14, 2012. That was 4 years, 8 months and 10 days ago. It was been in production the entire time without issue.

Provide a v1.0.0 release.

**Comment by grettke** [comment]
@punchagan I'm trying to commit and failing. I can't seem to figure where to change my commit access in metaweblog. What am I doing wrong?

```
ERROR: Permission to org2blog/metaweblog.git denied to grettke.
fatal: Could not read from remote repository.
```

**Comment by punchagan** [comment]
I don't know what's going on, but two ideas

- Can you check if the remote is one that allows commit? 

- Did you clone from the old repo and redirects are not working properly?

**Comment by punchagan** [comment]
Okay, looks like the setup of the org2blog organisation was not complete, and I had to add teams. You should be able to push now, @grettke

**Comment by grettke** [comment]
@punchagan I don't seem to have access privileges to check whether or not I've got privileges to commit here or not. Should I?

When I try pushing to the org2blog remote here is how it fails:
```
gcr@mara:~/src/metaweblog⮞ git remote -v
origin	github-gcr:org2blog/metaweblog.git (fetch)
origin	github-gcr:org2blog/metaweblog.git (push)
gcr@mara:~/src/metaweblog⮞ git push
ERROR: Permission to org2blog/metaweblog.git denied to grettke.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Am I doing it right?

**Comment by punchagan** [comment]
@grettke Looks like GitHub teams permissions aren't as straight forward as they used to be. I now made you an owner of the organization, and you should be able to do all the things that I am able to do. Please confirm.

**Comment by grettke** [comment]
@punchagan Confirmed. Just successfully committed. Thank you.
