### ISSUE TITLE
Package location

### ISSUE THREAD

**Issue by grettke** [org2blog/metaweblog#8]
@punchagan A while back I pushed for moving this package into it's own repository. That was a mistake—it is complex without any benefit because anyone can grab it from the org2blog repo. Well what is done is done, but it got me thinking about moving it back anyway: in the long run it is probably better to keep them together.

Any thoughts are welcomed here.

**Comment by grettke** [comment]
I see it was discussed here https://github.com/org2blog/org2blog/issues/52

**Comment by grettke** [comment]
It's been 8 years and not a single package depends on it on MELPA so I'll move it back. FWIW the MELPA package will end just being a single-file-reference that will get pulled right out of the org2blog repo so nothing will change for end users.
<img width="526" alt="Screenshot 2019-08-06 20 58 06" src="https://user-images.githubusercontent.com/2521647/62588929-290b0b80-b88d-11e9-9899-a13dad976f62.png">

**Comment by punchagan** [comment]
Sounds good! :+1:

**Comment by grettke** [comment]
It is now a package contained within the `org2blog` repo. So I'm going to close this once I make a note of it.
